// demo/WalkingTec.Mvvm.Next/ClientApp/packages/www-vue/src/views/pages/login/index.vue
<template>
  <a-layout class="app-layout-login">
    <a-layout :class="sampleClass">
      <a-layout-header>
        <img class="app-login-logo" :src="imgs.logo" alt="" height="48" />
      </a-layout-header>
      <a-layout-content>
        <div class="app-login-form">
          <a-form :form="form" @submit="handleSubmit">
            <h1 v-text="$GlobalConfig.settings.title"></h1>
            <a-form-item>
              <a-input
                size="large"
                v-decorator="[
                  'userName',
                  {
                    rules: [
                      { required: true, message: 'Please input your username!' }
                    ],
                    initialValue: 'admin'
                  }
                ]"
                placeholder="Username"
              >
                <a-icon
                  slot="prefix"
                  type="user"
                  style="color: rgba(0,0,0,.25)"
                />
              </a-input>
            </a-form-item>
            <a-form-item>
              <a-input
                size="large"
                v-decorator="[
                  'password',
                  {
                    rules: [
                      { required: true, message: 'Please input your Password!' }
                    ],
                    initialValue: '000000'
                  }
                ]"
                type="password"
                placeholder="Password"
              >
                <a-icon
                  slot="prefix"
                  type="lock"
                  style="color: rgba(0,0,0,.25)"
                />
              </a-input>
            </a-form-item>
            <a-form-item>
              <a-button
                :loading="UserStore.Loading"
                type="primary"
                html-type="submit"
                block
                size="large"
                class="login-form-button"
                >Log in</a-button
              >
            </a-form-item>
          </a-form>
        </div>
      </a-layout-content>
    </a-layout>
    <a-layout-footer>
      <a-row class=" app-login-links">
        <a-col class="ant-typography" :lg="18" :md="24">
          <h1>Quick Links</h1>
          <a-row>
            <a-col
              v-for="value in links"
              :key="value.name"
              :lg="6"
              :md="8"
              :xs="8"
              :sm="12"
            >
              <a :href="value.url" v-text="value.name" target="_blank"> </a>
            </a-col>
          </a-row>
        </a-col>
        <a-col :lg="6" :md="24">
          <img :src="imgs.code" alt="" width="88" height="88" />
        </a-col>
      </a-row>
      <div class="app-login-record">
        <a href="https://wtmdoc.walkingtec.cn/" target="_blank"> Help</a> © 2019
        WTM all rights reserved
      </div>
    </a-layout-footer>
  </a-layout>
</template>
<script lang="ts">
import lodash from "lodash";
import rootStore from "../../../rootStore";
import { Component, Prop, Vue } from "vue-property-decorator";
import code from "./code.png";
// @observer
@Component
export default class Login extends Vue {
  UserStore = rootStore.UserStore;
  form;
  imgs = this.$BasicData.imgs;
  links = this.$BasicData.links;
  get sampleClass() {
    return `app-login-back-${lodash.sample([1, 2, 3, 4, 5])}`;
  }
  beforeCreate() {
    this.form = this.$form.createForm(this, {});
  }
  handleSubmit(e) {
    e.preventDefault();
    this.form.validateFields(async (err, values) => {
      if (!err) {
        try {
          await this.UserStore.onLogin(values.userName, values.password);
        } catch (error) {
          this.$notification.error({
            key: "Login",
            message: "Login Error",
            description: error.message
          });
        }
      }
    });
  }
}
</script>
<style lang="less">
@import "./style.less";
</style>
<style scoped lang="less">
.app-login {
  min-height: 100vh;
}
.app-login-form {
  h1 {
    font-size: 50px;
    text-align: center;
    margin-bottom: 20px;
  }
}
.app-login-imgcode {
  .ant-popover-message-title {
    padding: 0;
  }
  .ant-popover-buttons {
    display: none;
  }
}
</style>

// demo/WalkingTec.Mvvm.ReactDemo/ClientApp/src/app/pages/login/index.tsx

import { Button, Form, Icon, Input, Popconfirm } from 'antd';
import { DesForm } from 'components/decorators';
import { default as GlobalConfig, default as globalConfig } from 'global.config';
import * as React from 'react';
import lodash from 'lodash';
import store from 'store/index';
import ImgCode from './imgCode';
import { LayoutLogin } from './layout';
import './style.less';

function hasErrors(fieldsError) {
  return Object.keys(fieldsError).some(field => fieldsError[field]);
}
@DesForm
export default class LoginDemo extends React.Component<any, any>{
  state = {
    loading: false,
    notCode: false, //!globalConfig.development,取消注释可以在发布环境出现滑块验证
    visible: false
  }
  onSubmit(e) {
    e.preventDefault();
    if (this.state.loading) {
      return
    }
    this.setState({ loading: true })
    this.props.form.validateFields(async (err, values) => {
      if (!err) {
        try {
          await store.User.Login(values);
        } catch (error) {
          this.setState({ loading: false })
        }
      }
    });
  }
  onSuccess() {
    this.setState({ notCode: false })
  }
  componentDidMount() {
    try {
      this.props.form.validateFields();
    } catch (error) {

    }
    lodash.delay(() => {
      // To disabled submit button at the beginning.
      try {
        this.props.form.validateFields();
      } catch (error) {

      }
    }, 500)
  }
  render() {
    const { getFieldDecorator, getFieldsError, isFieldTouched, getFieldError } = this.props.form;
    const userNameError = isFieldTouched('userid') && getFieldError('userid');
    const passwordError = isFieldTouched('password') && getFieldError('password');
    const disabled = hasErrors(getFieldsError())
    return (
      <LayoutLogin>
        <Form onSubmit={this.onSubmit.bind(this)} >
          <h1>{GlobalConfig.settings.title}</h1>
          <Form.Item
            validateStatus={userNameError ? 'error' : ''}
            help={userNameError || ''}
          >
            {getFieldDecorator('userid', {
              rules: [{ required: true, message: '请输入 用户名!' }],
              initialValue: globalConfig.development ? "admin" : ''
            })(
              <Input prefix={<Icon type="user" style={{ color: 'rgba(0,0,0,.25)' }} />} placeholder="Username" size="large" />
            )}
          </Form.Item>
          <Form.Item
            validateStatus={passwordError ? 'error' : ''}
            help={passwordError || ''}
          >
            {getFieldDecorator('password', {
              rules: [{ required: true, message: '请输入 密码!' }],
              initialValue: globalConfig.development ? "000000" : ""
            })(
              <Input prefix={<Icon type="lock" style={{ color: 'rgba(0,0,0,.25)' }} />} type="password" placeholder="Password" size="large" />
            )}
          </Form.Item>
          <div
            onMouseEnter={e => {
              if (this.state.notCode && !disabled) {
                this.setState({ visible: true })
              }
            }}
            onMouseOut={e => {
              if (!this.state.notCode) {
                this.setState({ visible: false })
              }
            }}>
            <Form.Item >
              <Popconfirm
                overlayClassName="app-login-imgcode"
                placement="top"
                title={<ImgCode onSuccess={this.onSuccess.bind(this)} key={String(this.state.notCode)} />}
                trigger="hover"
                visible={this.state.visible && this.state.notCode}
                icon="" >
                <Button
                  disabled={disabled || this.state.notCode}
                  type="primary" htmlType="submit" block size="large"
                  loading={this.state.loading}>
                  <span > Log in</span>
                </Button>
              </Popconfirm>
            </Form.Item>
          </div>
        </Form>
      </LayoutLogin>
    );
  }
}
