// demo/WalkingTec.Mvvm.Next/ClientApp/packages/www-vue/src/components/layout/content.vue
<template>
  <a-layout-content
    class="app-layout-content"
    :class="{ 'layout-content-tabs': $GlobalConfig.settings.tabsPage }"
  >
    <a-tabs
      v-if="$GlobalConfig.settings.tabsPage"
      class="layout-tabs"
      hideAdd
      size="small"
      type="editable-card"
      :activeKey="$route.fullPath"
      @edit="onEdit"
    >
      <a-tab-pane :key="'/'" :closable="false">
        <template #tab>
          <router-link to="/">
            <a-icon :type="'pic-right'" />
            <span>Home</span>
          </router-link>
        </template>
      </a-tab-pane>
      <a-tab-pane
        v-for="page in TabPages"
        :key="page.fullPath"
        :closable="true"
      >
        <template #tab>
          <router-link :to="page.path">
            <a-icon :type="page.icon || 'pic-right'" />
            <span v-text="page.name"></span>
          </router-link>
        </template>
        <!-- <router-view v-else></router-view> -->
      </a-tab-pane>
    </a-tabs>
    <div
      class="layout-page-view"
      :style="{
        height: height + 'px'
      }"
    >
      <keep-alive>
        <router-view />
      </keep-alive>
    </div>
  </a-layout-content>
</template>
<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import { Subscription, fromEvent } from "rxjs";
import { Debounce } from "lodash-decorators";
import { computed, observable, toJS, action } from "mobx";
import { create, persist } from "mobx-persist";
import rootStore from "../../rootStore";
import lodash from "lodash";
@Component({
  components: {}
})
export default class extends Vue {
  UserStore = rootStore.UserStore;
  hydrate = create({
    storage: window.localStorage, // 存储的对象
    jsonify: true, // 格式化 json
    debounce: 1000
  });
  // @persist("list")
  // @observable
  TabPages = [];
  onGetName(path) {
    return lodash.get(
      lodash.find(this.UserStore.Menus, ["path", path]),
      "name",
      path
    );
  }
  beforeMount() {
    // this.hydrate("layout", this);
  }
  mounted() {
    lodash.delay(() => {
      this.onPushTabPages();
    }, 300);
    this.onSetHeight();
    this.ResizeEvent = fromEvent(window, "resize").subscribe(e => {
      this.onSetHeight();
    });
  }
  updated() {
    this.onPushTabPages();
  }
  @action
  onPushTabPages() {
    if (
      this.$route.fullPath === "/" ||
      lodash.some(this.TabPages, ["fullPath", this.$route.fullPath])
    ) {
      return;
    }
    this.TabPages.push(
      lodash.merge({}, this.$route, { name: this.onGetName(this.$route.path) })
    );
    // console.log("extends -> onPushTabPages -> this.TabPages", this.TabPages)
  }
  @action
  onEdit(targetKey, action) {
    // this.$router.back();
    if (this.$route.fullPath === targetKey) {
      let index = lodash.findIndex(this.TabPages, ["fullPath", targetKey]);
      let fullPath = "/";
      if (index !== 0) {
        fullPath = lodash.get(this.TabPages, `[${index - 1}].fullPath`);
      }
      this.$router.replace(fullPath);
    }
    lodash.remove(this.TabPages, ["fullPath", targetKey]);
    this.TabPages = [...this.TabPages];
  }
  // 事件对象
  ResizeEvent: Subscription;
  height = 400;
  @Debounce(200)
  onSetHeight() {
    try {
      const offsetTop = lodash.get(this, "$el.firstChild.offsetTop", 0), //+ 5,
        innerHeight = window.innerHeight,
        height = innerHeight - offsetTop;
      this.height = height;
    } catch (error) {
      this.height = 400;
    }
  }
}
</script>
<style lang="less">
.layout-tabs {
  &.ant-tabs {
    position: initial;
  }
  .ant-tabs-nav-container {
    background: #fff;
  }
  .ant-tabs-bar {
    margin: 0;
    box-shadow: 0 1px 10px rgba(0, 21, 41, 0.08);
  }
  .ant-tabs-tabpane {
    padding: 0;
  }
  .ant-tabs-nav .ant-tabs-tab-active {
    font-weight: 400;
  }
}
.app-layout-content {
  margin: 8px;
  position: relative;
  &.layout-content-tabs {
    margin: 0;
  }
  a {
    text-decoration: none;
  }
}
// .layout-page-view {}
.layout-page-view > div.app-page {
  margin: 0 6px;
  padding-top: 6px;
}
// iframe.layout-page-view {
//   padding: 0;
// }
</style>

// demo/WalkingTec.Mvvm.ReactDemo/ClientApp/src/app/layout/default/content.tsx

import { Layout, Tabs } from 'antd';
import globalConfig from 'global.config';
import { observer } from 'mobx-react';
import * as React from 'react';
import { renderRoutes, matchRoutes } from 'react-router-config';
import { fromEvent, Subscription } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { observable, runInAction, action, toJS } from 'mobx';
import lodash from 'lodash';
import Store from 'store/index';
import { renderIconTitle } from './sider'
import { Help } from 'utils/Help';

const { Content } = Layout;
@observer
class Pages extends React.Component<any, any> {
  render() {
    if (globalConfig.tabsPage) {
      return <TabsPages {...this.props} />
    }
    return <SwitchPages {...this.props} />
  }
}
export default Pages
// class App extends React.Component<any, any> {
//   shouldComponentUpdate() {
//     return false
//   }
//   render() {
//     return <Pages {...this.props} />
//   }
// }


/**
 * 普通 页面 布局
 */
class SwitchPages extends React.Component<any, any> {
  componentDidMount() {
  }
  componentWillUnmount() {
  }
  componentDidUpdate() {
  }
  renderRoutes = renderRoutes(this.props.route.routes);
  render() {
    return (
      <Content className="app-layout-content" >
        {this.renderRoutes}
      </Content>
    );
  }
}
/**
 * tabs 页面布局
 */
@observer
class TabsPages extends React.Component<any, any> {
  TabsPagesStore = new TabsPagesStore();
  componentDidMount() {
    this.TabsPagesStore.pushTabPane(this.props.location.pathname);
  }
  componentWillUnmount() {
    this.TabsPagesStore.componentWillUnmount();
  }
  componentDidUpdate() {
    this.TabsPagesStore.pushTabPane(this.props.location.pathname);
    // console.log("TCL: TabsPages -> componentDidUpdate -> this.props", this.props)
  }
  getRoutes(pathname) {
    const router = matchRoutes(this.props.route.routes, pathname);
    // console.log("TCL: TabsPages -> getRoutes -> router", router)
    return {
      component: router[0].route.component,
      match: router[0].match
    }
  }
  onChange(event) {
    this.props.history.replace(event)
  }
  onEdit(event) {
    const path = this.TabsPagesStore.onClosable(event);
    if (lodash.eq(this.props.location.pathname, event))
      this.onChange(path)
  }
  render() {
    const tabPane = this.TabsPagesStore.tabPane;
    const height = this.TabsPagesStore.height;
    return (
      <Content className={`app-layout-content app-layout-content-tabs app-lockingTableRoll-${globalConfig.lockingTableRoll}`}>
        <Tabs
          activeKey={this.props.location.pathname}
          // size="small"
          className="app-layout-tabs"
          tabPosition={lodash.get(globalConfig, "tabPosition", "top") as any}
          onChange={this.onChange.bind(this)}
          animated={globalConfig.tabsAnimated}
          type="editable-card"
          onEdit={this.onEdit.bind(this)}
        >
          {tabPane.map(item => {
            const router = this.getRoutes(item.pathname);
            const props = { ...this.props, match: router.match };
            return <Tabs.TabPane
              tab={renderIconTitle({ Icon: item.icon, Text: item.title })}
              key={item.pathname}
              closable={item.closable}
              style={{ height: height }}>
              {React.createElement(router.component, props)}
            </Tabs.TabPane>
          })}
        </Tabs>
      </Content>
    );
  }
}
class TabsPagesStore {
  constructor() {
  }
  componentWillUnmount() {
    this.resize.unsubscribe();
  }
  @observable height = this.getHeight();
  @observable tabPane = [{
    title: '首页',
    pathname: "/",
    closable: false,
    icon: "home",
  }];
  @action
  pushTabPane(pathname) {
    // console.log("TCL: TabsPagesStore -> pushTabPane -> pathname", pathname)
    if (lodash.some(this.tabPane, item => lodash.eq(item.pathname, pathname))) return;
    const menu = lodash.find(Store.Meun.ParallelMenu, ['Url', pathname]);
    // console.log("TCL: TabsPagesStore -> pushTabPane -> menu", menu)
    const title = lodash.get(menu, 'Text', "Null")
    const icon = lodash.get(menu, 'Icon', "appstore")
    this.tabPane.push({
      title: title,//renderIconTitle(menu || { Text: "NULL", Icon: "appstore", Id: Help.GUID() }),
      pathname,
      closable: true,
      icon
    });
  }
  @action
  onClosable(pathname) {
    const index = lodash.findIndex(this.tabPane, ['pathname', pathname]);
    const path = lodash.get(this.tabPane, `[${index - 1}].pathname`, "/");
    lodash.remove(this.tabPane, ['pathname', pathname]);
    return path
  }
  getHeight() {
    return window.innerHeight - (lodash.some(["top", "bottom"], data => lodash.eq(data, globalConfig.tabPosition)) ? 90 : 50);
  }
  resize = fromEvent(window, "resize").pipe(debounceTime(200)).subscribe(e => {
    const height = this.getHeight()
    if (this.height != height) {
      runInAction(() => this.height = height)
    }
  });
}
